### ISSUE TITLE
Callback error type void | Error does not work with TypeScript 2.0

### ISSUE THREAD

**Issue by felixfbecker** [goenning/typed-generic-pool#6]
https://github.com/goenning/typed-generic-pool/blob/master/index.d.ts#L7
For TypeScript 2.0, this should be `null | Error`. To keep compat with TS 1.8 _and_ TS 2.0, it should be changed to `any`.

**Comment by goenning** [comment]
Using `any` doesn't seem right. Can't we just use `Error` just like node's typings [1]? 

Btw, I don't remember why we've used `void` before. Seems to be useless in this case, isn't it?

[1] https://github.com/types/env-node/blob/master/6/node.d.ts#L1395

**Comment by felixfbecker** [comment]
From a JS perspective that is not correct though. You can throw anything (even a string), not just `Error`. That is why TypeScript also types the error in a `catch` block as `any` (and not `Error`). Using just `Error` would not work in TS 2 with `strictNullChecks`, you could not call it with `null` then. The node typings are actually wrong here, I guess dns isnt used that much :D The only way to make it compatible with TS1.8 and TS2 here is to use `any`

**Comment by goenning** [comment]
That makes sense, thanks for the clarification. Let's leave it as that for now until TS 1.8 is deprecated. Right?

**Comment by felixfbecker** [comment]
Yes, thanks :)
